-- DROP ALL TABLES 

DROP TABLE IF EXISTS plays
DROP TABLE IF EXISTS games
DROP TABLE IF EXISTS memberships
DROP TABLE IF EXISTS decks
DROP TABLE IF EXISTS possessions
DROP TABLE IF EXISTS players
DROP TABLE IF EXISTS versions
DROP TABLE IF EXISTS cards